# -*- coding: utf-8 -*-
"""AlgoritmoGenetico_helloWorld.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JB-iqrZMnH6Y6Owrl2-IkwYqj5WSYv2F
"""

import random as rand

origen= " abcdefghijklmnñopqrstuvwxyzABCDEFGHIJKLMNÑOPQRSTUVWXYZ"
destino= "HOLA MUNDO HORA A TODOS"

def definirPoblacion(longitud):
  return rand.sample(origen,longitud)

for i in range(10):
  print(definirPoblacion(len(destino)))

def funcionObjetivo(individuo):
  list(zip(destino, individuo))
  valor = sum(1 for letraDes, letraInd in zip(destino, individuo) if letraDes==letraInd)
  return valor

def cruce(ind):
  individuoCruzado=ind.copy()
  puntoCruce = rand.randint(0,len(ind)-2)
  #print("punto cruce", puntoCruce)
  individuoCruzado[puntoCruce:puntoCruce+2]=destino[puntoCruce:puntoCruce+2]
  return individuoCruzado

def mutacion(individuo):
  individuoMutado = individuo.copy()
  indice = rand.randint(0,len(individuo)-1)
  nuevoValor= rand.choice(origen)
 # print("Actual:[",indice,"]",individuoMutado[indice],"!= Destino:[",indice,"]",destino[indice]," nuevo",nuevoValor)
  if individuoMutado[indice] != destino[indice]:
    individuoMutado[indice] = nuevoValor
  return individuoMutado

padre= definirPoblacion(len(destino))
print("padre ",padre)
adaptacionPadre=funcionObjetivo(padre)
cont=0
iteraciones=0
while True:
  iteraciones+=1
  hijo= mutacion(padre)
  adaptacionHijo= funcionObjetivo(hijo)
  #print("G",cont,":",hijo)
  cont+=1

  if adaptacionPadre>=adaptacionHijo:
    continue
  if adaptacionHijo>=len(destino):
    break
  padre=hijo
  adaptacionPadre=adaptacionHijo
print("G",cont,":",hijo)