# -*- coding: utf-8 -*-
"""AlgoritmoGeneticoModelo_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GxNH3JcdtbTcjXxCQVS69kBPPpnxsRoE

***Algoritmo genético que busca optimizar una población para encontrar el mejor individuo a partir de un modelo definido***
"""

import random as rd

"""**Definir individuo**"""

def getIndividuo(min,max,tamano):
  return [rd.randint(min,max) for x in range(tamano)]

"""**Definir población**"""

def getPoblacion(numero):
  return [getIndividuo(0,valorMaximo,tamano) for i in range (numero)]

"""**Calcular adaptación** (Función objetivo)"""

def CalcularAdaptacion(individuo):
  valor=0
  for i in range(len(individuo)):
    if modelo[i]==individuo[i]:
      valor+=1
  return valor

"""**Realizar Cruce**"""

def cruce(lPoblacion,lPadres):
  for i in range(len(lPoblacion)-1):
    puntoCruce = rd.randint(0, tamano -1)
    #print("punto cruce %s" % (puntoCruce))
    lPoblacion[i][:puntoCruce]=lPadres[0][1][:puntoCruce]
    lPoblacion[i][puntoCruce:]=lPadres[1][1][puntoCruce:]
  return lPoblacion

"""**Realizar Mutación**"""

def mutacion(listaCruzados):
  for i in range(len(listaCruzados)-1):
     if rd.random() <= probMutacion:
      punto = rd.randint(0, tamano-1)
      nuevo_valor = rd.randint(0, valorMaximo)
      while nuevo_valor == listaCruzados[i][punto]:
       nuevo_valor = rd.randint(0, valorMaximo)
      listaCruzados[i][punto]=nuevo_valor
  return listaCruzados

"""**Método Ver**"""

def verLista(lista, texto):
  print("\n"+texto)
  for i in lista:
    print (i)

"""---
**Inicio**

**Flujo del algoritmo genético**
"""

#Parámetros iniciales
tamano=10
valorMaximo=3
tamanoPoblacion=20

numMejores=4
iteraciones=200
probMutacion=0.8

modelo=getIndividuo(0,valorMaximo,tamano)
print("Modelo %s" % (modelo))

#-----------Generar la población ------------------
listaPoblacion = getPoblacion(tamanoPoblacion)
verLista(listaPoblacion, "---Población inicial ---")

for j in range(iteraciones):
  #---------Calculo de adaptación---------
  listaValorados = [(CalcularAdaptacion(i),i) for i in listaPoblacion]
  listaOrdenados=sorted(listaValorados, reverse=True)
  #verLista(listaOrdenados, "---Población Valorada ---")
  #print(listaOrdenados[0][0])

  #---------Selección---------"
#  listaSeleccionados = listaOrdenados[:(len(listaOrdenados) - numMejores)]
  listaSeleccionados = listaOrdenados[:numMejores]
  listaPadres=rd.sample(listaSeleccionados,2)
  #verLista(listaPadres, "---Individuos seleccionados como padres ---")

  #---------Cruce-------------"
  listaPoblacionCruzada=cruce(listaPoblacion,listaPadres)
  #verLista(listaPoblacionCruzada,"---Población Cruzada ---")

  #---------Mutación-------------"
  listaPoblacionMutada=mutacion(listaPoblacionCruzada)
  #verLista(listaPoblacionMutada,"---Población Mutada ---")
  listaPoblacion=listaPoblacionMutada

#verLista(listaPoblacion,"---Población Final ---")

#---mejor individuo---
listaMejores = [(CalcularAdaptacion(i),i) for i in listaPoblacion]
listaMejores=sorted(listaMejores, reverse=True)
print("\n\nModelo %s" % (modelo))
print("\nMejor individuo después de "+ str(iteraciones) + " iteraciones")
print(listaMejores[0])